[package]
name = "bee"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Qrcode
qrcode = "0.12.0"
image = "0.24.2"

# web
actix-web = "4.1.0"
